
export const RESPONSE_INGREDIENT_REQUEST = "RESPONSE_INGREDIENT_REQUEST";
export const RESPONSE_INGREDIENT_FAILURE = "RESPONSE_INGREDIENT_FAILURE";
export const RESPONSE_INGREDIENT_SUCCESS = "RESPONSE_INGREDIENT_SUCCESS";

export const RESPONSE_RECIPE_REQUEST = "RESPONSE_RECIPE_REQUEST";
export const RESPONSE_RECIPE_FAILURE = "RESPONSE_RECIPE_FAILURE";
export const RESPONSE_RECIPE_SUCCESS = "RESPONSE_RECIPE_SUCCESS";


// export const ingredients = [
//     "Chicken",
//     "Beef",
//     "Fish",
//     "Shrimp",
//     "Eggs",
//     "Rice",
//     "Tomatoes",
//     "Cheese",
//     "Broccoli",
//     "Pasta",
//     "Potatoes",
//     "Lentils",
//     "Bell Peppers",
//     "Spinach",
//     "Carrots",
//     "Onions",
//     "Garlic",
//     "Zucchini",
//     "Mushrooms",
//     "Cilantro",
//     "Basil",
//     "Oregano",
//     "Olive Oil",
//     "Coconut Milk",
//     "Soy Sauce",
//     "Lemon",
//     "Honey",
//     "Peanut Butter",
//     "Tofu",
//     "Tofu"
// ];

// export const ingredientData = [
//     [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0], // Chicken Stew
//     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], //  Beef Stir Fry
//     // "Spinach and Mushroom Quesadilla",
//     // "Vegetable Soup",
//     // "Chicken Quinoa Bowl",
//     // "Grilled Cheese Sandwich",
//     // "Vegetable Quesadilla",
//     // "Creamy Mushroom Risotto",
//     // "Chicken Tikka Masala",
//     // "Roasted Cauliflower",
//     // "Stuffed Peppers",
//     // "Cauliflower Rice",
//     // "Turkey Meatballs",
//     // "Chicken Enchiladas",
//     // "Baked Ziti",
//     // "Black Bean Soup",
//     // "Quinoa Salad",
//     // "Corn Chowder",
//     // "Chicken Burrito Bowl",
//     // "Beetroot Salad",
//     // "Greek Salad",
//     // "Lentil Salad",
//     // "Tomato Basil Soup",
//     // "Chicken Alfredo",
//     // "Shrimp Fried Rice",
//     // "Eggplant Parmesan",
//     // "Chicken Caesar Salad",
//     // "Mushroom Stroganoff",
//     // "Pasta Primavera",
//     // "Stuffed Zucchini",
//     // "Thai Chicken Curry",
//     // "Butternut Squash Soup",
//     // "Chicken and Rice Casserole",
//     // "Vegetable Stir Fry",
//     // "Spinach Salad with Feta",
//     // "Coconut Curry Lentil Soup",
//     // "Salmon Fillet with Asparagus",
//     // "BBQ Chicken Pizza",
//     // "Egg Drop Soup",
//     // "Sweet Potato Mash",
//     // "Tuna Salad",
//     // "Minestrone Soup",
//     // "Chicken Pot Pie",
//     // "Roasted Brussels Sprouts",
//     // "Macaroni and Cheese",
//     // "Chicken Fajitas",
//     // "Beef Tacos",
//     // "Shrimp Tacos",
//     // "Ratatouille",
//     // "Chicken and Broccoli Stir Fry",
//     // "Potato Leek Soup",
//     // "Caprese Salad",
//     // "Baked Salmon with Lemon",
//     // "Veggie Burger",
//     // "Chicken Noodle Soup",
//     // "Stuffed Bell Peppers",
//     // "Sloppy Joes",
//     // "Chickpea Salad",
//     // "Teriyaki Chicken",
//     // "Vegetable Fried Rice",
//     // "Grilled Shrimp Skewers",
//     // "Chocolate Chip Cookies",
//     // "Banana Bread",
//     // "Carrot Ginger Soup",
//     // "Chilli Con Carne",
//     // "Beef and Broccoli Stir Fry",
//     // "Corn Salad",
//     // "Chicken Shawarma",
//     // "Garlic Mashed Potatoes",
//     // "Pesto Pasta",
//     // "French Onion Soup",
//     // "Egg Salad Sandwich",
//     // "Lemon Garlic Chicken",
//     // "Vegetarian Chili",
//     // "Tomato Salad with Mozzarella",
//     // "Ratatouille Pasta",
//     // "Thai Green Curry",
//     // "Buffalo Cauliflower Wings",
//     // "Cabbage Rolls",
//     // "Spaghetti Carbonara",
//     // "Chicken and Dumplings",
//     // "Roasted Vegetable Medley",
//     // "Grilled Chicken Salad",
//     // "Cauliflower Buffalo Bites",
//     // "Peanut Butter Cookies",
//     // "Clam Chowder",
//     // "Pasta Salad",
//     // "Quiche Lorraine",
//     // "Asian Noodle Salad",
//     // "Tofu Stir Fry",
//     // "Baked Potatoes",
//     // "Coconut Rice",
//     // "Stuffed Mushrooms",
//     // "Chicken Burrito",
//     // "Fettuccine Alfredo",
//     // "Sausage and Peppers",
//     // "Ratatouille Casserole",
//     // "Veggie Tacos",
//     // "Grilled Vegetable Sandwich",
//     // "Chocolate Mousse"
   
// ];

// export const recipeNames = [
//     "Chicken Stew",
//     "Beef Stir Fry",
//     "Spinach and Mushroom Quesadilla",
//     "Vegetable Soup",
//     "Chicken Quinoa Bowl",
//     "Grilled Cheese Sandwich",
//     "Vegetable Quesadilla",
//     "Creamy Mushroom Risotto",
//     "Chicken Tikka Masala",
//     "Roasted Cauliflower",
//     "Stuffed Peppers",
//     "Cauliflower Rice",
//     "Turkey Meatballs",
//     "Chicken Enchiladas",
//     "Baked Ziti",
//     "Black Bean Soup",
//     "Quinoa Salad",
//     "Corn Chowder",
//     "Chicken Burrito Bowl",
//     "Beetroot Salad",
//     "Greek Salad",
//     "Lentil Salad",
//     "Tomato Basil Soup",
//     "Chicken Alfredo",
//     "Shrimp Fried Rice",
//     "Eggplant Parmesan",
//     "Chicken Caesar Salad",
//     "Mushroom Stroganoff",
//     "Pasta Primavera",
//     "Stuffed Zucchini",
//     "Thai Chicken Curry",
//     "Butternut Squash Soup",
//     "Chicken and Rice Casserole",
//     "Vegetable Stir Fry",
//     "Spinach Salad with Feta",
//     "Coconut Curry Lentil Soup",
//     "Salmon Fillet with Asparagus",
//     "BBQ Chicken Pizza",
//     "Egg Drop Soup",
//     "Sweet Potato Mash",
//     "Tuna Salad",
//     "Minestrone Soup",
//     "Chicken Pot Pie",
//     "Roasted Brussels Sprouts",
//     "Macaroni and Cheese",
//     "Chicken Fajitas",
//     "Beef Tacos",
//     "Shrimp Tacos",
//     "Ratatouille",
//     "Chicken and Broccoli Stir Fry",
//     "Potato Leek Soup",
//     "Caprese Salad",
//     "Baked Salmon with Lemon",
//     "Veggie Burger",
//     "Chicken Noodle Soup",
//     "Stuffed Bell Peppers",
//     "Sloppy Joes",
//     "Chickpea Salad",
//     "Teriyaki Chicken",
//     "Vegetable Fried Rice",
//     "Grilled Shrimp Skewers",
//     "Chocolate Chip Cookies",
//     "Banana Bread",
//     "Carrot Ginger Soup",
//     "Chilli Con Carne",
//     "Beef and Broccoli Stir Fry",
//     "Corn Salad",
//     "Chicken Shawarma",
//     "Garlic Mashed Potatoes",
//     "Pesto Pasta",
//     "French Onion Soup",
//     "Egg Salad Sandwich",
//     "Lemon Garlic Chicken",
//     "Vegetarian Chili",
//     "Tomato Salad with Mozzarella",
//     "Ratatouille Pasta",
//     "Thai Green Curry",
//     "Buffalo Cauliflower Wings",
//     "Cabbage Rolls",
//     "Spaghetti Carbonara",
//     "Chicken and Dumplings",
//     "Roasted Vegetable Medley",
//     "Grilled Chicken Salad",
//     "Cauliflower Buffalo Bites",
//     "Peanut Butter Cookies",
//     "Clam Chowder",
//     "Pasta Salad",
//     "Quiche Lorraine",
//     "Asian Noodle Salad",
//     "Tofu Stir Fry",
//     "Baked Potatoes",
//     "Coconut Rice",
//     "Stuffed Mushrooms",
//     "Chicken Burrito",
//     "Fettuccine Alfredo",
//     "Sausage and Peppers",
//     "Ratatouille Casserole",
//     "Veggie Tacos",
//     "Grilled Vegetable Sandwich",
//     "Chocolate Mousse"
// ];