
export const PAGE_HOME = "PAGE_HOME";
export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_ABOUT = "PAGE_ABOUT";


export const PAGE_MEAL_PLAN = "PAGE_MEAL_PLAN";
export const PAGE_INGREDIENT_BASED_RECIPE_SUGGESTIONS = "PAGE_INGREDIENT_BASED_RECIPE_SUGGESTIONS";
export const PAGE_RECIPES_BY_CATEGORY = "PAGE_RECIPES_BY_CATEGORY";

