export const RESPONSE_LOGIN_REQUEST = "RESPONSE_LOGIN_REQUEST";
export const RESPONSE_LOGIN_FAILURE = "RESPONSE_LOGIN_FAILURE";
export const RESPONSE_LOGIN_SUCCESS = "RESPONSE_LOGIN_SUCCESS";

export const RESPONSE_REGISTRATION_REQUEST = "RESPONSE_REGISTRATION_REQUEST";
export const RESPONSE_REGISTRATION_FAILURE = "RESPONSE_REGISTRATION_FAILURE";
export const RESPONSE_REGISTRATION_SUCCESS = "RESPONSE_REGISTRATION_SUCCESS";

export const RESPONSE_INGREDIENT_REQUEST = "RESPONSE_INGREDIENT_REQUEST";
export const RESPONSE_INGREDIENT_FAILURE = "RESPONSE_INGREDIENT_FAILURE";
export const RESPONSE_INGREDIENT_SUCCESS = "RESPONSE_INGREDIENT_SUCCESS";

export const RESPONSE_RECIPE_REQUEST = "RESPONSE_RECIPE_REQUEST";
export const RESPONSE_RECIPE_FAILURE = "RESPONSE_RECIPE_FAILURE";
export const RESPONSE_RECIPE_SUCCESS = "RESPONSE_RECIPE_SUCCESS";

export const RESPONSE_CATEGORY_REQUEST = "RESPONSE_CATEGORY_REQUEST";
export const RESPONSE_CATEGORY_FAILURE = "RESPONSE_CATEGORY_FAILURE";
export const RESPONSE_CATEGORY_SUCCESS = "RESPONSE_CATEGORY_SUCCESS";
